# Generated by Django 5.2 on 2025-05-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
